name: 'Package actions'
description: 'Publish actions as OCI artifacts to GHCR and sign it.'
author: 'Ruchika Jain'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/package-action'
    default: ${{ github.repository }}
#   token:
#     description: >
#       Personal access token (PAT) used to fetch the repository with write package scope.
#     default: ${{ github.token }}
  semver:
    description: 'Release version'
    default: '1.0.1'
  package-name: 
    description: 'The name of the package to be published to GHCR'
    default: ${{ github.repository }}
outputs:
  package-name: # id of output
    description: 'The name of package published to GHCR'   
runs:
  using: 'node16'
  main: 'dist/index.js'
